### ISSUE TITLE
Callback from RMUnify not parsed / processed

### ISSUE THREAD

**Issue by mcansky** [Hampei/omniauth-saml-rmunify#1]
In omniauth initializer :

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :saml_rmunify,
           assertion_consumer_service_url: '/auth/saml_rmunify/callback',
           issuer: "http://lvh.me:3000/auth/rm_unify/callback",
           idp_sso_target_url: "https://sts.platform.rmunify.com/issue/saml/?binding=redirect",
           idp_cert_fingerprint: "66:cb:2d:02:cd:81:f1:b1:03:22:6b:a0:21:cd:8e:69:0c:5e:f4:25"
end
```

The login button pointing to /saml_rmunify properly sends to the sso_target_url where users can proceed with authentication and then send back to the call back.

In that callback the params does include a SAMLResponse but nothing seems to be processed by Omniauth as request.env["omniauth.auth"] stays nil.

A quick look through https://github.com/onelogin/ruby-saml/tree/v0.7.1 does show ways to process the data "by hand" but I would assume that it should happen out of the box with omniauth ?

Am I missing something in the config here to allow proper parsing of the SAMLResponse ?

_update_ : the callback is handled for now with a very limited action that just dumps the response and request.env .

**Comment by Hampei** [comment]
Omniauth should indeed set the request.env["omniauth.auth"], where my code mostly just sets the  request.env["omniauth.auth"].info part. 

You might want to have a look at the SAMLResponse contents, since it could be wrong somehow. One of the things that went wrong for me at first is that they didn't allow a port-number in the callback url, but since you are getting a callback that has been at least partially fixed. Another thing that might go wrong is that the license string format used to be very strict ("/appname/package/school_type/term"), but has been relaxed so you might be getting a different one. None of this should prevent you having a a bunch of request.env["omniauth.auth"].raw_info set though.

Looking at the code an exception would be thrown if you haven't selected displayname, nor username, nor firstname to be send through in https://dashboard.rmunify.com/Publisher/ManageApp. 
But I would have expected an error to appear in the logs at that point at the very least. I'll fix that issue though.

You can parse the SAMLResponse with this function, print it to the logs to see if it looks ok: 

```
def decode_raw_saml_response(response)
  require "base64"
  if response =~ /^</
    return response
  elsif (decoded  = Base64.decode64(response)) =~ /^</
    return decoded
  elsif (inflated = inflate(decoded)) =~ /^</
    return inflated
  end
  raise "Couldn't decode SAMLResponse"
end
```

**Comment by Hampei** [comment]
Pushed a new version that won't crash if displayname, username nor firstname are send in the callback.

**Comment by mcansky** [comment]
I was still not able to get the _request.env['omniauth.auth']_ to be present.

Instead, using Onelogin Saml Ruby gem I was able to extract the data as needed :

```
  def saml_settings
    settings = Onelogin::Saml::Settings.new

    settings.assertion_consumer_service_url = 'http://lvh.me:3000/auth/rm_unify/callback'
    settings.issuer = "http://lvh.me/auth/rm_unify/callback"
    settings.idp_sso_target_url = "https://sts.platform.rmunify.com/issue/saml/?binding=redirect"
    settings.idp_cert_fingerprint = "66:cb:2d:02:cd:81:f1:b1:03:22:6b:a0:21:cd:8e:69:0c:5e:f4:25"
    settings.name_identifier_format = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
    settings
  end

  def rm_unify_response
    @response_hash ||= Onelogin::Saml::Response.new(params[:SAMLResponse])
    @response_hash.settings = saml_settings
    @response_hash
  end
```

The object returned by _rm_unify_response_ can then be used to check for authentication (as described in https://github.com/onelogin/ruby-saml#the-initialization-phase).

I am wondering what's still causing omni.auth to fail. A conflict in versions ?

Local versions :
- omniauth (1.2.1)
- omniauth-facebook (1.6.0)
- omniauth-google-oauth2 (0.2.4)
- omniauth-oauth2 (~> 1.1)
- omniauth-oauth (1.0.1)
- omniauth-oauth2 (1.1.1)
- oauth2 (~> 0.8.0)
- omniauth-saml (1.1.0)
- ruby-saml (~> 0.7.2)
- omniauth-saml-rmunify (2.0.1)
- omniauth-twitter (0.0.15)

---

_for the story_

I had to spend a couple of hours playing back and forth with the issuer value to make it work again. Apparently while it's supposed to allow "anything" it's still pretty limited.

Here is what I found to work :
- the issuer needs to be an url
- the issuer needs to be the same value as the acs url but without a custom port

**Comment by Hampei** [comment]
Are you using devise or omniauth directly? 
It sounds like the callback url is not going through omniauth first.

With devise your routes file should look something like this, to make the input be prepared by omniauth.: 

```
devise_for :members, controllers: {
  omniauth_callbacks: 'members/omniauth_callbacks' }
```

**Comment by mcansky** [comment]
we are using omniauth directly

**Comment by Hampei** [comment]
And I'm guessing the facebook omniauth is working fine? So it's probably not an omniauth issue. 

Can you paste the contents of the login response? So I can see if the format is what I expect?

You can also try to use omniauth-saml directly and see if you can get that to work. As said, my gem is just very light wrapper around omniauth-saml, with some easier names and license parsing.

**Comment by mcansky** [comment]
The other omniauth backends do work fine yes.

The login response works, the issue now is with getting proper token and expire info.

**Comment by Hampei** [comment]
is it working with this gem or with your own workaround? What was the problem?

For token and expire info, you'll need to look at  omniauth-saml, I'm not touching those variables. 

I'm also not using them in my system, so if it does turn out it's rm-unify specific, you might want to add it to this gem and send me a pull request.

**Comment by mcansky** [comment]
I think in the end I am just using this gem for the login route and redirect to RM Unify,

All the rest is tied with omniauth saml / Onelogin saml.
