### ISSUE TITLE
Question on logout

### ISSUE THREAD

**Issue by TheHelmsman** [Hampei/omniauth-saml-rmunify#3]
Hi,

I tried to implement a proper log-out  for RM Unify using your explanation (https://github.com/hampei/omniauth-saml-rmunify/wiki/single_logout) and couple of other guides that your work derives from: 
https://github.com/onelogin/ruby-saml#single-log-out
https://gist.github.com/mcansky/e165aecf64d5c39e71cb

But non of them seems to be working ATM.

My log-out controller which called by IdP in case when RM Unify user log-outs from their dashboard looks like this:

```
class RmunifyLogoutController < ApplicationController

  require 'ruby-saml'

  def index

    logout_request = OneLogin::RubySaml::SloLogoutrequest.new(params[:SAMLRequest])
    Rails.logger.debug ">> IdP logout_request: #{logout_request}"
    if !logout_request.is_valid?
      Rails.logger.error ">> IdP initiated LogoutRequest was not valid!"
      render plain: logout_request.errors, status: 400
    end

    uid = logout_request.name_id
    Rails.logger.debug ">> IdP initiated LogoutRequest, name_id: #{uid}"
    Rails.logger.debug ">> IdP initiated LogoutRequest, id: #{logout_request.id}"

    # Re-Enable when request will work
    # if session["rm_unify_record"].present?
    #   reset_session
    #   cookies.delete(:remember_me) 
    # end

    Rails.logger.debug ">> IdP RM_UNIFY_SETTINGS: #{rmunify_settings}"
    settings = OneLogin::RubySaml::Settings.new(rmunify_settings)
    Rails.logger.debug ">> IdP settings: #{settings}"
    Rails.logger.debug ">> IdP params[:RelayState]: #{params[:RelayState]}"
    #logout_response = OneLogin::RubySaml::SloLogoutresponse.new.create(settings, logout_request.id, nil, :RelayState => params[:RelayState])
    logout_response = OneLogin::RubySaml::SloLogoutresponse.new.create(settings, logout_request.id, nil, :RelayState => params[:RelayState])
    Rails.logger.debug ">> IdP logout_response: #{logout_response}"
    redirect_to logout_response
  end
```

```
  def rmunify_settings
    settings = {
      assertion_consumer_service_url: "http://domain:3000/auth/saml_rmunify/callback",
      issuer:                         "https://domain/#{Rails.env}",
      idp_sso_target_url:             "http://sts.platform.rmunify.com/issue/saml/?binding=redirect",
      idp_cert_fingerprint:           "66:cb:2d:..."
    }
    settings
  end
end
```

All works, until it comes to line 31 where I get Internal Server Error 500, with following print:

```
# current_user: 3335 / RMUnifyA
  School Load (0.1ms)  SELECT `schools`.* FROM `schools` WHERE `schools`.`id` = 1236 LIMIT 1
>> IdP logout_request: #<OneLogin::RubySaml::SloLogoutrequest:0x00000009537b00>
>> IdP initiated LogoutRequest, name_id: <correct name id>
>> IdP initiated LogoutRequest, id: <correct id>
>> IdP RM_UNIFY_SETTINGS: {:assertion_consumer_service_url=>"<correct settings>", :issuer=>"<correct settings>", :idp_sso_target_url=>"http://sts.platform.rmunify.com/issue/saml/?binding=redirect", :idp_cert_fingerprint=>"66:cb:..."}
>> IdP settings: #<OneLogin::RubySaml::Settings:0x00000009504570>
>> IdP params[:RelayState]: /issue/samlSLO?binding=redirect
Created SLO Logout Response: <samlp:LogoutResponse ID='_b93e1380-XXXX....' InResponseTo='_796a471c-XXX...' IssueInstant='2014-12-XXX...' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'><samlp:Status><samlp:StatusCode Value='urn:oasis:names:tc:SAML:2.0:status:Success'/><samlp:StatusMessage>Successfully Signed Out</samlp:StatusMessage></samlp:Status><saml:Issuer>https://app.petrasplanetforschools.com/development</saml:Issuer></samlp:LogoutResponse>
Completed 500 Internal Server Error in 13.8ms

NoMethodError (undefined method `+' for nil:NilClass):
  app/controllers/rmunify_logout_controller.rb:31:in `index'

Line 31 in my code, looks like this:
logout_response = OneLogin::RubySaml::SloLogoutresponse.new.create(settings, logout_request.id, nil, :RelayState => params[:RelayState])
```

It seems that SLOLogoutrequest created correctly, at least I can see it's print in server log, but then for some mysterious reason I'm getting Server Error 500 instead of redirecting to log-out request that was created

Any help from your side is highly appreciated.

P.S. I'm not using Devise in this implementation, so I was experimenting first to get proper settings setup for log-out request. Now settings looks ok, or at least in log-out request print I can see the correct values, which indicates that the settings were parsed correctly.

Thank you in advance.

**Comment by Hampei** [comment]
Two extra settings I have are: 
base_url:                       "https://sts.platform.rmunify.com",
idp_slo_target_url:             'https://sts.platform.rmunify.com/issue/samlSLO/?binding=redirect',

That might be causing the nil error. 
Otherwise you'll need to get the full stack trace instead of just the application trace. since the + is clearly not called on line 31, but in the RubySAML gem.

**Comment by TheHelmsman** [comment]
You're right - that was the reason, when I added these two lines, it started working.
It is very sad that all settings to make RM Unify work needs to be discovered by using method of trial and error, and there are no clear documentation on all mandatory field for settings and settings format as well.
During my investigations I also discovered that defining settings like this: 
def saml_settings
    idp_metadata_parser = OneLogin::RubySaml::IdpMetadataParser.new
    # Returns OneLogin::RubySaml::Settings prepopulated with idp metadata
    settings = idp_metadata_parser.parse_remote("https://sts.platform.rmunify.com/SAMLMetadata/Unify-Live-Metadata.xml")
    settings.assertion_consumer_service_url = "http://domain:3000/auth/saml_rmunify/callback"
    settings.issuer                         = "https://domain/#{Rails.env}"
    settings.name_identifier_format         = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
    # Optional for most SAML IdPs
    settings.authn_context = "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
    settings
 end
won't work - you'll get a parser error

But anyway, thank you very much!

I think you can add this information to your Wiki as well.
The final implementation that works for me looks like this:
def rmunify_settings
    settings = {
      assertion_consumer_service_url: "http://domain:3000/auth/saml_rmunify/callback",
      issuer:                         "https://domain/#{Rails.env}",
      idp_sso_target_url:             "http://sts.platform.rmunify.com/issue/saml/?binding=redirect",
      idp_cert_fingerprint:           "66:cb:2d...",
      base_url:                       "https://sts.platform.rmunify.com",
      idp_slo_target_url:             "https://sts.platform.rmunify.com/issue/samlSLO/?binding=redirect"
    }
    settings
  end
